### PR TITLE
replace random - if you like it

### PR DESCRIPTION
**Pull request by Soldy**
Signed-off-by: Soldy <4786022+Soldy@users.noreply.github.com>

### CODE REVIEW

**Comment by SatYu26** [comment]
@Soldy random.js is not working as expected. It adds the commits but not the number of commits it should add. it just adds one commit everytime

**Comment by SatYu26** [comment]
I have made the required change and now its working fine.

**Comment by Soldy** [comment]
> I have made the required change and now its working fine.

Sorry I was rushed.
This is why you need a test ;)

**Comment by SatYu26** [comment]
> > I have made the required change and now its working fine.
> 
> Sorry I was rushed.
> This is why you need a test ;)

Yes thats true, but no issues

**Pull request merged**
